// LOCALHOST
###
GET http://localhost:3000/contacts
###
GET http://localhost:3000/contacts/62695959bf6456e2e1e36df4
### 
GET http://localhost:3000/contacts/62695959bf6456e2e1e36df5
###
GET http://localhost:3000/contacts/62695959bf6456e2e1e36df6

// PRODUCTION - HEROKU
###
GET https://backend-dev-2.herokuapp.com/contacts